### PR TITLE
More resilient reporting when revdep's DESCRIPTION is missing or empty

### LINKED ISSUE #295: NA's in results for `cloud_check()`
I just ran `cloud_check()` for r-lib/memoise@fb66ecd, and had some `NA` names and versions in the results. I ran it twice and got these `NA`s both times. They show up immediately, shortly after the job is started.

```
> job <- "0e574f15-d4c1-4c8b-ad48-3fba99975576"
> cloud_summary(job)
ℹ Syncing results to revdep/cloud.noindex/0e574f15-d4c1-4c8b-ad48-3fba99975576
ℹ Extracting results
ℹ Comparing results
✓ autota 0.1.3                           ── E: 0     | W: 0     | N: 1                                        
✓ available 1.0.4                        ── E: 0     | W: 0     | N: 1    
✓ BARIS 1.1.1                            ── E: 0     | W: 0     | N: 1    
✓ baytrends 2.0.2                        ── E: 0     | W: 0     | N: 1    
✓ biolink 0.1.7                          ── E: 0     | W: 0     | N: 0    
✓ BWStest 0.2.2                          ── E: 0     | W: 0     | N: 0    
✓ civis 3.0.0                            ── E: 0     | W: 0     | N: 0    
✓ codemetar 0.1.9                        ── E: 0     | W: 0     | N: 1    
✓ conflicted 1.0.4                       ── E: 0     | W: 0     | N: 1    
E NA NA                                  ── E: 1/1   | W: 1/1   | N: 1/1  
✓ covr 3.5.1                             ── E: 0     | W: 0     | N: 0    
✓ cultevo 1.0.2                          ── E: 0     | W: 0     | N: 1    
✓ cymruservices 0.5.0                    ── E: 0     | W: 0     | N: 0    
✓ datarobot 2.17.1                       ── E: 0     | W: 0     | N: 0    
✓ DeLorean 1.5.0                         ── E: 0     | W: 0     | N: 3    
✓ devtools 2.3.2                         ── E: 1     | W: 0     | N: 0    
✓ dm 0.1.10                              ── E: 0     | W: 0     | N: 0    
✓ ecmwfr 1.3.0                           ── E: 0     | W: 0     | N: 0    
✓ eia 0.3.6                              ── E: 0     | W: 0     | N: 0    
✓ ffscrapr 1.2.1                         ── E: 0     | W: 0     | N: 0    
✓ fgeo.x 1.1.4                           ── E: 0     | W: 0     | N: 0    
✓ fishtree 0.3.3                         ── E: 0     | W: 0     | N: 0    
✓ functools 0.2.0                        ── E: 0     | W: 0     | N: 0    
x GetBCBData 0.5                         ── E: 0  +1 | W: 0     | N: 1    
✓ GetQuandlData 0.1.0                    ── E: 0     | W: 0     | N: 1    
✓ googleAnalyticsR 0.8.0                 ── E: 0     | W: 0     | N: 0    
✓ googleAuthR 1.3.1                      ── E: 0     | W: 0     | N: 0    
✓ GSED 2.5                               ── E: 0     | W: 0     | N: 0    
✓ gWidgets2RGtk2 1.0-7                   ── E: 0     | W: 0     | N: 0    
I gWidgets2tcltk 1.0-6                   ── E: 0  +1 | W: 0     | N: 0    
✓ heemod 0.14.0                          ── E: 0     | W: 0     | N: 0    
✓ huxtable 5.1.1                         ── E: 1     | W: 0     | N: 1    
✓ jpmesh 2.0.0                           ── E: 0     | W: 0     | N: 1    
E NA NA                                  ── E: 1/1   | W: 1/1   | N: 1/1  
✓ kimisc 0.4                             ── E: 0     | W: 0     | N: 1    
✓ LAGOSNE 2.0.2                          ── E: 0     | W: 0     | N: 0    
✓ latte 0.2.1                            ── E: 0     | W: 0     | N: 0    
✓ LCAvarsel 1.1                          ── E: 0     | W: 0     | N: 1    
✓ LDATS 0.2.7                            ── E: 0     | W: 0     | N: 0    
✓ m2r 1.0.2                              ── E: 0     | W: 0     | N: 0    
✓ metR 0.9.0                             ── E: 0     | W: 0     | N: 1    
✓ mindicador 0.1.5                       ── E: 0     | W: 0     | N: 1    
✓ mixggm 1.0                             ── E: 0     | W: 0     | N: 1    
✓ mlr 2.18.0                             ── E: 0     | W: 0     | N: 2    
✓ MODISTools 1.1.1                       ── E: 0     | W: 0     | N: 0    
✓ move 4.0.6                             ── E: 0     | W: 0     | N: 0    
✓ nat.templatebrains 1.0                 ── E: 0     | W: 0     | N: 0    
✓ nhdR 0.5.3                             ── E: 0     | W: 0     | N: 0    
E NA NA                                  ── E: 1/1   | W: 1/1   | N: 1/1  
✓ officedown 0.2.0                       ── E: 0     | W: 0     | N: 0    
✓ opencage 0.1.4                         ── E: 0     | W: 0     | N: 0    
✓ OpenML 1.10                            ── E: 0     | W: 0     | N: 0    
✓ osfr 0.2.8                             ── E: 0     | W: 0     | N: 0    
✓ packageRank 0.3.5                      ── E: 0     | W: 0     | N: 0    
✓ phateR 1.0.4                           ── E: 0     | W: 0     | N: 1    
✓ phenocamr 1.1.4                        ── E: 0     | W: 0     | N: 1    
✓ piggyback 0.0.11                       ── E: 0     | W: 0     | N: 0    
✓ pkgdown 1.6.1                          ── E: 0     | W: 0     | N: 1    
✓ pkgsearch 3.0.3                        ── E: 0     | W: 0     | N: 0    
✓ polite 0.1.1                           ── E: 0     | W: 0     | N: 0    
✓ povcalnetR 0.1.1                       ── E: 0     | W: 0     | N: 1    
✓ prcbench 0.9.1                         ── E: 0     | W: 0     | N: 1    
✓ RcppEigenAD 1.0.0                      ── E: 0     | W: 0     | N: 2    
✓ rfishbase 3.0.4                        ── E: 0     | W: 0     | N: 1    
✓ rgho 2.0.1                             ── E: 0     | W: 0     | N: 0    
E NA NA                                  ── E: 1/1   | W: 1/1   | N: 1/1  
✓ rsoi 0.5.4                             ── E: 0     | W: 0     | N: 0    
✓ RSQLite 2.2.2                          ── E: 0     | W: 0     | N: 1    
✓ rtrek 0.3.2                            ── E: 0     | W: 0     | N: 2    
E NA NA                                  ── E: 1/1   | W: 1/1   | N: 1/1  
✓ saeRobust 0.2.0                        ── E: 0     | W: 0     | N: 0    
✓ SamplingStrata 1.5-1                   ── E: 0     | W: 0     | N: 0    
✓ scopr 0.3.3                            ── E: 0     | W: 0     | N: 0    
✓ SIDES 1.15                             ── E: 0     | W: 0     | N: 0    
✓ simfinapi 0.1.0                        ── E: 0     | W: 0     | N: 0    
✓ simfinR 0.2.2                          ── E: 0     | W: 0     | N: 0    
✓ slouch 2.1.4                           ── E: 0     | W: 0     | N: 0    
✓ snotelr 1.0.4                          ── E: 0     | W: 0     | N: 0    
✓ surveillance 1.18.0                    ── E: 0     | W: 0     | N: 2    
✓ SVN 1.0.1                              ── E: 0     | W: 0     | N: 0    
✓ taxadb 0.1.0                           ── E: 0     | W: 0     | N: 1    
✓ TotalCopheneticIndex 1.0.1             ── E: 0     | W: 0     | N: 2    
✓ tradestatistics 1.1                    ── E: 0     | W: 0     | N: 0    
✓ TreeDist 1.2.1                         ── E: 0     | W: 0     | N: 0    
✓ weathercan 0.4.0                       ── E: 0     | W: 0     | N: 2    
```

Here's what one of the result objects from `cloud_results()` looks like:

```
[[66]]
$package
Package 
     NA 

$status
[1] "E"

$old
── R CMD check results ────────────────────────────────────────────────────────────────────────────── NA NA ────
Duration: 

> NA
  

> NA
  

> NA
  

1 error x | 1 warning x | 1 note x

$new
── R CMD check results ────────────────────────────────────────────────────────────────────────────── NA NA ────
Duration: 

> NA
  

> NA
  

> NA
  

1 error x | 1 warning x | 1 note x

$version
[1] NA

attr(,"class")
[1] "rcmdcheck_error"

### LINKED ISSUE #310: Bizarre reporting for failure (of a package named "do")
I just had a fairly successful cloud revdep run with usethis. But one of the two packages that failed is named "do" (which seems like a bad idea, but that is beside the point).

Reporting failure for this package, specifically, seems to be a problem. I'm not sure if it's something about how it fails or ... could it somehow have something to do with it's name?

Here's my `revdep/` directory right after this run:

https://github.com/r-lib/usethis/tree/ded1495b6489e93e1ec88e1ad117f7f4c2d6b2fc/revdep

In the README, you can see that this package's name appears as `NA`.

In `cran.md`, it inexplicably is not reported alongside the other failure (butcher https://github.com/tidymodels/butcher/issues/201).

In `failures.md`, it is also reported as `NA` and no details are given.

### PR DESCRIPTION
**Pull request by jennybc**
Fixes #295, fixes #310

I had a very conservative goal here: replace the `NA`s we see for problem packages in `cloud_summary()`, `revdep/README.md` and `revdep/failures.md` with a package name. I have succeeded in this.

There are still quite a few problems with how these problem packages are being reported (or, rather, are not necessarily being reported), but I think other issues already capture some of the more substantive problems (such as #317, #301). 

I was developing against a specific cloud revdep run for usethis, so I had authentic weird stuff to work with. All the `NA`s in my case were due to `DESCRIPTION` being non-existent or empty, for a revdep package. That was explained by the package being on Bioconductor, not CRAN, or requiring a higher R version than we were checking with. Or because shit happens? There was at least one package that had bizarre results for no identifiable reason and this self-resolved in a future revdep run.

### CODE REVIEW

**Comment by jennybc** [comment]
The GHA failure looks like a problem in `r-lib/actions@v2`, not anything in this PR.

**Comment by DavisVaughan** [comment]
This worked for me in tidyr! https://github.com/tidyverse/tidyr/commit/312b6d1567533f23554591cd48a7abc5ef58dcd4

File: R/cloud.R [hunk 1]
```diff
@@ -311,7 +311,11 @@ cloud_check_result <- function(check_log, description, dependency_error) {
         notes = NA_character_,
 
         description = description$str(normalize = FALSE),
-        package     = description$get("Package"),
+        # DESCRIPTION can exist but be empty, e.g. for a Bioconductor package
+        # or a when package's minimum R version isn't met
+        # at the VERY LEAST, let's get a package name
+        package     = description$get("Package") %|%
+                        sub("[.]Rcheck", "", basename(check_dir)),
```
Comment (hadley) [inline R/cloud.R:318]:
```suggestion
        package     = description$get_field("Package", sub("[.]Rcheck$", "", basename(check_dir))),
```
